Paginate = 4
baseURL = "/"
description = "test"
languageCode = "ru-ru"
theme = "kube"
title = "# Все можно в Тае"
[[menu.main]]
name = "Блог"
url = "/blog/"
weight = -100
[params]
author = "команда Все можно в Тае"
email = "myemail@myaddress.xxx"
github = ""
instagram = "https://www.instagram.com/vsemozhnovtae/"
rsslink = "/index.xml"
twitter = ""
